### ISSUE TITLE
8, 9th episode recording

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#10]
Date: 2016/08/31 19:30-21:00(Wed)
Venue: TBD(probably recruit building at Ginza)
Guest: @thagikura
Contents: 
- https://github.com/google/flexbox-layout

**Comment by thagikura** [comment]
Here are other topics I have in mind that you may be interested in.
- How android apps development works at Google sub topics like:
  - Tools (VCS, Build ... )
  - Code reviews
  - Testing
  - Code convention
  - etc
- Android views in general
- Identity apps
  - [Google Prompt](http://lifehacker.com/google-prompt-lets-you-use-two-factor-authentication-wi-1782413235) 
  - [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en) 
- Security features like
  - Keystore
  - Fingerprint
- [Firebase Test Lab](https://firebase.google.com/docs/test-lab/) (Used as part of the CI for the FlexboxLayout) 
- Misc
  - Hobbies other than coding

Btw, I'm totally okay if I comment this issue in English or Japanese. Please let me know which language you prefer.

**Comment by hotchemi** [comment]
Thx! I really wanna talk about `Code reviews` and also GitHub, Gerrit and so on💃
And when it comes to the language, actually either is fine for us but basically we use English to hide contents from Japanese listeners hehe...(hopefully)

**Comment by thagikura** [comment]
Fair enough, I'll write in English.

Okay, let's also talk about the development process 👍. I'll be prepared for that.
