### ISSUE TITLE
10,11 episode

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#11]
- Date: 9/30
- Time: 19:30-21:00
- Venue: [GranTokyo South Tower](https://www.google.co.jp/maps/place/%E3%80%92100-0005+%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%8D%83%E4%BB%A3%E7%94%B0%E5%8C%BA%E4%B8%B8%E3%81%AE%E5%86%85%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%99%E2%88%92%EF%BC%92/@35.688951,139.767551,14z/data=!4m5!3m4!1s0x60188bfb66dca6e7:0xe5617e38e31a5853!8m2!3d35.6786466!4d139.7673837?hl=ja)
- Guest: @KeithYokoma

**Comment by hotchemi** [comment]
@KeithYokoma @hkurokawa What we're gonna talk about?😃

**Comment by hkurokawa** [comment]
Hmm. How about each one of us brings one topic? Then we can have a talk about three topics.

Mine would be RxJava 2.0, definitely 😎

**Comment by KeithYokoma** [comment]
## 1. About our development
- Architecture
  - MVP
  - Mortar & Flow (why? how? pros and cons)
  - Rx
  - State management
- Hacks and tweaks
  - AIDL
  - Media framework on Android Auto
  - Notification framework
  - Themes and Styles
  - Drawing views on overlay (WindowManager)
- Wercker CI
  - Docker image management
  - Java license
- Analytics, A/B Testing and Experiments
- Localization

## 2. About Silicon Valley
- Climate
- Lifestyle
- Work

## 3. Other tech topics
- Debugging tools/methodology
  - e.g. How to find and fix a bug in complicated state machines
- Remote testing
  - OpenSTF

## 4. Off-topic
- Cycling, training, gymnastics
- TechBooster

**Comment by hotchemi** [comment]
Topic candidates:
- [RxJava 2.0.0 Release Candidate 2 available now](https://twitter.com/RxJava/status/772836198842851328)
- [Kotlin 1.0.4 is here](https://blog.jetbrains.com/kotlin/2016/09/kotlin-1-0-4-is-here/)
- [Introducing the Realm Mobile Platform: Realtime Sync Plus Fully Open Source Database](https://realm.io/news/introducing-realm-mobile-platform/)
- [hotchemi/tiamat](https://github.com/hotchemi/tiamat)

**Comment by hotchemi** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0

**Comment by hotchemi** [comment]
http://www.reactive-streams.org/

**Comment by hotchemi** [comment]
http://takezoe.hatenablog.com/entry/20150217/p1

**Comment by hotchemi** [comment]
https://youtrack.jetbrains.com/issue/KT-13499#tab=Changes
https://github.com/jetbrains/kotlin/commit/0181dd000d1fa0d1a1fdc0308ad0a937b2fe206c

**Comment by hotchemi** [comment]
https://realm.io/jp/news/introducing-realm-mobile-platform/

**Comment by hotchemi** [comment]
https://speakerdeck.com/jakewharton/looking-ahead-to-rxjava-2-droidcon-nyc-2016

**Comment by hkurokawa** [comment]
RxJava 2.0

https://github.com/reactive-streams/reactive-streams-jvm/
http://okapies.hateblo.jp/entry/2015/06/26/024505
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
http://fragmentedpodcast.com/episodes/053-jake-wharton-on-rxjava-2/
https://speakerdeck.com/jakewharton/looking-ahead-to-rxjava-2-droidcon-nyc-2016
