### ISSUE TITLE
12,13 episode

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#13]
- Date: 10/25(Tue)
- Time: 19:30-21:00
- Venue: [GranTokyo South Tower](https://www.google.co.jp/maps/place/%E3%80%92100-0005+%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%8D%83%E4%BB%A3%E7%94%B0%E5%8C%BA%E4%B8%B8%E3%81%AE%E5%86%85%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%99%E2%88%92%EF%BC%92/@35.688951,139.767551,14z/data=!4m5!3m4!1s0x60188bfb66dca6e7:0xe5617e38e31a5853!8m2!3d35.6786466!4d139.7673837?hl=ja)
- Guest: Suzuki-san

**Comment by hkurokawa** [comment]
Just an idea.
- About DevFest
  - How come?
  - What's GDG
  - Future plan
- Google and Android engineer
  - Japan and other countries
  - Planned events
- GDE
  - Congrats to wasabeef-san
  - What's GDE
- Material Design
  - Status
    - How many apps are designed in a material way?
  - Common mistakes
  - Goods and bads

**Comment by taquo** [comment]
My memo
- DevFest
  - Developer Festival run by community all over the world.
  - https://developers.google.com/events/devfest/
  - Over 100 events all over the world. 
  - GDG is Google Developer Group. 103 countries, 570 chapters, and 3600+ events in last 6 month.
  - There are 9 GDGs chapters in Japan
- GDE
  - Google Developers Experts : External experts of Google Technologies. We often sees GDE is a passionate speaker of GDG events.
- Material Design
  - Over 1 million apps using Material Design on Google Play.
  - Project Kennedy (2011)
  - Holo (Android 4.0 ICS API 14) (2011)
  - Common mistakes
  - FAB
  - Hamburger Menu
  - Cards
  - Raised button
  - Material Design Award
  - C CHANNEL won Material Design Award 
  - https://design.google.com/articles/material-design-awards-2016/
