### ISSUE TITLE
Decide 2nd episode agenda

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#2]
Any opinion?

**Comment by hotchemi** [comment]
@kgmyshin @hkurokawa Let's determine the next episode shownote!

**Comment by hkurokawa** [comment]
Here is my idea:

#### 1. About Google I/O
- Keynote
  - No surprise
  - [Rebuild: 143: Bavorware (takoratta, N)](http://rebuild.fm/143/)
- Instant Apps
  - [インストール不要のネイティブアプリ：Android Instant Apps | TechBooster](http://techbooster.org/android/application/17376/)
- New development tools with Android Studio 2.2 preview (ConstraintLayout, etc.)
  - Jack annotation processor support
  - Runtime permission code generation
- Others
  - Awareness API
  - 野外フェス
  - セッション聴くべきか Sandbox や Office Hours を活用すべきか問題
    - ATAP は行きたかった

#### 2. A particular topic suggested by @kgmyshin
- Android におけるチーム開発

Any comments are welcome!

**Comment by kgmyshin** [comment]
メンターもだけど、「チーム開発 for android」みたいな感じだと話しやすそう

**Comment by hkurokawa** [comment]
なるほど。じゃあ、そっちにしましょう!

**Comment by hotchemi** [comment]
FirebaseとかWhat's new in support libraryもちょっと話したい
https://www.youtube.com/watch?v=tb2GZ3Bh4p8
https://www.youtube.com/watch?v=w45y_w4skKs

**Comment by kgmyshin** [comment]
Android におけるチーム開発
- 現状のチームはどんな感じ？
- 理想のチームはどんなのだと思う？
- 新卒などのメンタリング
- 新規プロジェクトの進め方(自分の場合は少人数かつAndroid未熟な人ばかりのチームの時にどうしたかとか話せます。逆に優秀なメンバーばかりの場合の進め方とかは聞きたい)
  - コードレビュー
  - 設計関連どうするか問題
  - どういう体制でやってるか(今は○人でスクラムでやってる、理想は○人くらいでXXXなやり方だと良さそうとか)
- エンハンスの体制
  - 新規プロジェクトの時と変えたほうがいいかとか?

**Comment by hotchemi** [comment]
### 3: Google IO 2016

[@kgmyshin](https://twitter.com/kgmyshin)さんをゲストに迎えて、GoogleIO、Instant Apps、Android Studio 2.2 Preview、Awareness APIなどについて話しました。
- [GoogleIO 2016](https://speakerdeck.com/hkurokawa/android-studio-2-dot-2-and-beyond)
- [Android Instant Apps](https://developer.android.com/topic/instant-apps/index.html)
- [Android Studio 2.2 Preview - New UI Designer & Constraint Layout](http://android-developers.blogspot.jp/2016/05/android-studio-22-preview-new-ui.html)
  - [New Layout Editor with Constraint Layout](http://tools.android.com/tech-docs/layout-editor)
  - [[Google I/O 2016] ConstraintLayout ~ Android の新 Layout](https://tech.recruit-mp.co.jp/event/post-10235/)
  - [[Google I/O 2016] より使いやすくなったDataBindingの新機能とTips紹介](https://tech.recruit-mp.co.jp/event/post-10069/)
- [Android Studio 2.2 and Beyond](https://speakerdeck.com/hkurokawa/android-studio-2-dot-2-and-beyond)
- [Google Awareness API](https://developers.google.com/awareness/)

### 4: Team Android Development

[@kgmyshin](https://twitter.com/kgmyshin)さんをゲストに迎えて、チーム開発、設計、DDD、育成などについて話しました。
- [unskilled team development for android](https://speakerdeck.com/kgmyshin/unskilled-team-development-for-android)
- [[ Android ] - これからの「設計」の話をしよう](https://tech.recruit-mp.co.jp/mobile/android-architecture/)
- [モバイル開発組織変遷モデル](http://hotchemi.hateblo.jp/entry/2016/04/28/024034)

**Comment by hkurokawa** [comment]
良いと思います。眺めていて Episode 3.5 はなくても良いかなぁという気分になりました。

**Comment by hotchemi** [comment]
http://hotchemi.hateblo.jp/entry/2016/04/28/024034

**Comment by hotchemi** [comment]
https://speakerdeck.com/hkurokawa/android-studio-2-dot-2-and-beyond
