### ISSUE TITLE
Episode 25, 26

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#24]
- Date: 6/1(Thu)
- Time: 20:00-21:00
- Venue: [三井住友海上テプコビル](https://www.google.com/maps/place/%E6%97%A5%E6%9C%AC,+%E3%80%92104-0031+%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%BA%AC%E6%A9%8B%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%96%E2%88%92%EF%BC%91/@35.677833,139.7691059,17z/data=!3m1!4b1!4m5!3m4!1s0x60188be2c1fbcabf:0x5a85f24e8a1e2b25!8m2!3d35.677833!4d139.7712946?hl=ja-JP)
- Guest: @hak

---

**ゲストへの質問や聞きたい事があればこちらまでfeedbackをお待ちしております**

**Comment by hkurokawa** [comment]
# 概要案

## 前半（TensorflowLite と Google I/O の舞台裏）
- TensorflowLite のセッションについて [Android Meets TensorFlow: How to Accelerate Your App with AI (Google I/O '17) - YouTube](https://www.youtube.com/watch?v=25ISTLhz0ys)
  - モバイル向けの課題
     - メモリバス
     - 端末が熱くなる問題？
  - 機械学習におけるサーバー側とモバイル側の分担
  - プラットフォームにTensorflowLiteやNN APIは載るのか？
  - ラジオ体操
  - hak さんが、どのあたりを担当したのか
  - Vulkan との関係
  - 参加者からの反応
- I/O の舞台裏
  - どうやってセッションが決まるのか
  - 事前準備・リハーサル
  - キーノートで初めて発表される内容について（たとえば TensorflowLite はキーノートで発表されるので概要には含められないのでは？）
- hak さんのいまのお仕事について（話せる範囲で）

## 後半（雑談・I/Oの感想）
- I/O の運営が格段に改善された話
- 今年のキーノートの感想
  - Mobile First to AI First
  - IRとしてのI/O
- Androidまわりのニュース
  - Kotlin のオフィシャルサポート
  - Architecture Components
  - O の影の薄さ :bowing_man: 
- AMD Ryzen
- 機械学習における GPU
- [詳報：トヨタが頼った謎のAI半導体メーカー：日経ビジネスオンライン](http://business.nikkeibp.co.jp/atcl/report/17/ai/051700001/?P=1&utm_content=buffer9e69a&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

**Comment by hotchemi** [comment]
自分が気になったTopics.
- [What’s New in Android: O Developer Preview 2 & More](https://android-developers.googleblog.com/2017/05/whats-new-in-android-o-developer.html)
- [Android architecture](https://android-developers.googleblog.com/2017/05/android-and-architecture.html)
- [Android Studio 3.0 Canary 1](https://android-developers.googleblog.com/2017/05/android-studio-3-0-canary1.html)
- [Here comes Treble: A modular base for Android](https://android-developers.googleblog.com/2017/05/here-comes-treble-modular-base-for.html)
- [What’s new from Firebase at Google I/O 2017](https://firebase.googleblog.com/2017/05/whats-new-from-firebase-at-google-io.html)
- [flutter](https://flutter.io/)

**Comment by hkurokawa** [comment]
AlphaGo と TPU の話

- [最強囲碁AI「AlphaGo」全勝　世界最強棋士も敵わず - ITmedia NEWS](http://www.itmedia.co.jp/news/articles/1705/27/news038.html)

**Comment by hotchemi** [comment]
AlphaGo話したいですね！

**Comment by hotchemi** [comment]
## Firebase

- Crashlytics is going to be integrated into Firebase as the main crash reporting solution.
- https://opensource.google.com/projects/firebase-sdk
- Cloud functions now integrate with Hosting to provide full dynamic webapps.
- Performance Monitor (beta)
- Test Lab
  - Adding first-class support for games: game tests can now run on test lab.
  - Test lab now allows you to simulate different network conditions, like 4G, 3G, or slower ones.
- Firebase Alpha
  - You can now sign up to get the new stuff before it's released and provide feedback about it at https://services.google.com/fb/forms/firebasealphaprogram/
