### ISSUE TITLE
ep27, 28

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#26]
- Date: 6/30(Fri)
- Time: 19:30-21:00
- Venue: [Mitsui sumitomo kaijyo building](https://www.google.com/maps/place/%E6%97%A5%E6%9C%AC,+%E3%80%92104-0031+%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%BA%AC%E6%A9%8B%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%96%E2%88%92%EF%BC%91/@35.677833,139.7691059,17z/data=!3m1!4b1!4m5!3m4!1s0x60188be2c1fbcabf:0x5a85f24e8a1e2b25!8m2!3d35.677833!4d139.7712946?hl=ja-JP)
- Guest: @kittinunf

**Comment by kittinunf** [comment]
Thank for having me as a guest. Looking forward to this! :) :)

**Comment by hotchemi** [comment]
rough agenda of episode:

### 1st(30min)

- Introduction of kittinunf
  - Who you are, what you've done, what are you working on etc...
- Kotlin
  - When did you get into Kotlin?
  - How you're using Kotlin in Cookpad
  - How proceeding migration from Java
    - any why?
  - Pros and Cons of migration/adoption of Kotlin
  - How to train other members?
  - Which part of features do you prefer?
  - About your library: https://github.com/kittinunf/Fuel, https://github.com/kittinunf/Result

### 2nd(30min)

- Cookpad global development style
  - architecture/library/tools
  - Localization
  - Remote work?
  - How to communicate among several offices
- [Android Talks @ Cookpad!!](https://www.meetup.com/Android-Talks-Cookpad/events/240229714/)
  - How did it start off?
  - What's the future of it?
- Misc
  - your hobby, some techie news or on those lines...

**Comment by hotchemi** [comment]
### News

- https://blog.jetbrains.com/kotlin/2017/06/kotlin-1-1-3-is-out/
- https://blog.jetbrains.com/kotlin/2017/06/kotlinnative-v0-3-is-out/
- https://blog.jetbrains.com/kotlin/2017/06/early-access-program-for-kotlin-1-2-has-been-started/

**Comment by hotchemi** [comment]
## Show notes:

https://www.youtube.com/watch?v=OfJdtWzwERk
http://slides.com/kittinunf/kotlin-and-android-development#/
