### ISSUE TITLE
ep32, 33

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#29]
- Date: 09/07(Thu)
- Time: 19:30-21:00
- Venue: [Mitsui sumitomo kaijyo building](https://www.google.com/maps/place/%E6%97%A5%E6%9C%AC,+%E3%80%92104-0031+%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%BA%AC%E6%A9%8B%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%96%E2%88%92%EF%BC%91/@35.677833,139.7691059,17z/data=!3m1!4b1!4m5!3m4!1s0x60188be2c1fbcabf:0x5a85f24e8a1e2b25!8m2!3d35.677833!4d139.7712946?hl=ja-JP)
- Guest: @gfx

**Comment by gfx** [comment]
👀

**Comment by hotchemi** [comment]
my brief notes here:

- 自己紹介、最近何やってるか
- https://github.com/maskarade/Android-Orma
  - なぜ開発し始めたのか、ユーザー
  - 特徴、Ormaを使うメリットとはなにか、他ORMとの比較
  - サポート体制等
  - 今後の展望
  - Roomとの比較、Architecture componentsに関して思う所あればどうぞ
- https://github.com/maskarade/
  - http://gfx.hatenablog.com/entry/2017/08/14/104301
  - what is maskarade
  - どうして作ったのか?
  - OSSのメンテナンスやモチベーションに関して思うところをぜひ！
  - OSSの開発、どうやって時間を確保している？
- Misc
  - https://github.com/retropiler/retropiler, https://github.com/maskarade/gradle-android-ribbonizer-plugin など
  - TypeScript, Markdownに関して何か語れる事があれば
  - Speeeの技術顧問等何かあれば

**Comment by hotchemi** [comment]
何か追記あればお願いします！なければこれベースでいこうと思います！

**Comment by gfx** [comment]
いいと思います！！

PDの話も触れましょう（自然に触れそうだけど）

**Comment by hotchemi** [comment]
ありがとうございます！
PD organizationの話はmaskaradeの話の際にちょい触れます〜
