### ISSUE TITLE
EP 36

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#30]
- Date: 09/26(Thu)
- Time: 19:30-21:00
- Venue: [Mitsui sumitomo kaijyo building](https://www.google.com/maps/place/%E6%97%A5%E6%9C%AC,+%E3%80%92104-0031+%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%BA%AC%E6%A9%8B%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%96%E2%88%92%EF%BC%91/@35.677833,139.7691059,17z/data=!3m1!4b1!4m5!3m4!1s0x60188be2c1fbcabf:0x5a85f24e8a1e2b25!8m2!3d35.677833!4d139.7712946?hl=ja-JP)
- Guest: @atsuko-fukui

### Show notes

- http://muumuutech.hatenablog.com/entry/2017/09/04/074557
- https://github.com/RettyEng/redux-kt

**Comment by atsuko-fukui** [comment]
話そうと思っていること：

- 自己紹介
- Reduxはいいぞ
    - データを一箇所に集約かつ単一方向データフロー
    - 一度ロードした情報はStateに保持されるので次回利用時にAPIコールをまたず利用できる
    - Activity / Fragment を跨いで情報を更新できる
    - unit test 書きやすい（純粋関数なので）
- ReduxとKotlinの相性の良さ
    - state定義 (nullable or not)
    - data classのcopy methodめっちゃ便利
- 会社でkotlinで作ったreduxのOSS Library公開しました
    - pull requestをいただいてrx java 2 をbindingしたモジュールも作りました

**Comment by hotchemi** [comment]
ありがとうございます！気になっている事メモ:

- 差分更新的な仕組みはどうやって担保している？(Stateの更新のたびにrenderが呼ばれる問題への対処)
- animationとかどう管理している？
- reduxで全部管理していてOOMとかになった事は？
- 非同期処理どうしている？
- redux middleware的なものを社内で作ってたりするのか(redux-thunk, redux-persist的な)
- https://github.com/pardom/redux-kotlin を使わず自作した理由
