### ISSUE TITLE
6th episode

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#5]
Guest: @takahirom
Recording date: 
Topic: 
Shownote:

**Comment by hotchemi** [comment]
What are we going to talk about @hkurokawa @takahirom? View stuff?

**Comment by takahirom** [comment]
How about Android Studio?
これまでの話題も含めて考えると、Android Studioとかどうでしょう？
ただ口頭で伝わらないかもしれませんが、、
この機能が便利とかこういう使い方してるとか、新機能とかとか

**Comment by hotchemi** [comment]
いいっすね！prefix codingの話とかプラグインとかの話は結構盛り上がりそう！

**Comment by hkurokawa** [comment]
黒帯本の中で takahirom さんが担当している箇所の話は聞いてみたいです。Android Studio のあたりでしょうか? あと Vector Drawable の話とかお詳しい印象があるので、そのへんとかどうでしょう。

個人的には Yahoo! Japan 内部の話(たとえば黒帯エンジニアの話とか)や takahirom さんの来歴、日頃どうやって情報収集しているのか、という話は興味あるので、後半でそのあたりの柔らかい話もしてみたいですね。

**Comment by takahirom** [comment]
いいですね！ちょっと土曜日ぐらいまでに内容を箇条書きか何かでまとめてみます！

持ちネタになりそうなものを一応出しておきます。
Android Studio(プラグインとか)
Android N
Support Library (VectorDrawableCompat,CoordinatorLayout)
Gradle
WebView(つらさ)

**Comment by takahirom** [comment]
今までのものだと、何かテーマがあったので、そこでいうのはAndroid Studioが良さそうな気がしています。

以下のようなイメージでどうでしょうか？
ちょっと全く経験がないので、ガンガンこうした方がよいなど教えていただきたいです！
- 自己紹介
  (後半で本や黒帯制度についてなどを話しましょうーという感じですすめる)
- Android Studio
  - 使っているバージョン、環境
  - よく使うショートカット
  - Android Studio 2.1 2.2
  - プラグイン
    ….(思いつき次第追加します)
- 本の執筆について
  - 担当部分は？
  - 本の中で意識した部分は？
- 黒帯制度ってどういう感じ？すぐになれるもの？(ちょっと勘違いされていたら申し訳ないのですが自分は黒帯ではないです。)
- 普段の開発ってどういうふうに行っているか？
- 注目しているAndroidの技術は？(ここでVectorDrawableなど)
- どうやって情報収集しているか？

**Comment by hotchemi** [comment]
@takahirom @hkurokawa ざっくり整理してみました。

## Ep6: Android Studio(前半30分)
- takahiromさん自己紹介(所属、今やってるアプリ(できれば)、黒帯本に関してちらっと触れる) 
- Android Studio
  - 使っているバージョン、環境
  - よく使うショートカット
    - 内蔵ターミナル(Option + F12) Complete Current Statement(Shift + Cmd + Enter)
    - Quick Document F1
    - Recent Files command + e
    - Toggle Bookmark F3
    - Show Bookmarks command +Search Everywhere
    - shift*2（2回素早く押す） F3
    - Next Highlighted Error F2
    - Mouse less driven development https://vimeo.com/98922030
  - Android Studio 2.1 2.2
  - プラグイン ….(思いつき次第追加します)
    - https://github.com/takahirom/android-postfix-plugin
- VectorDrawableCompat,CoordinatorLayout系の話…具体的に何話すとかありますか？
- Android Wearとか？

## Ep7: Yahoo style development(後半30分)
- 本の執筆について
  - 担当部分は？
  - 本の中で意識した部分は？
- 黒帯制度ってどういう感じ？すぐになれるもの？(ちょっと勘違いされていたら申し訳ないのですが自分は黒帯ではないです。)
- 普段の開発ってどういうふうに行っているか？
- 育成
- どうやって情報収集しているか？
- PokemonGO!!!

**Comment by hkurokawa** [comment]
良さそう。黒帯本、読んでいて、デザインとかユーザーインタビューの話が入っているのが面白かったので、どうしてそういう構成になったのか、とか聞けると嬉しいです。あとは、社内の Android エンジニアの育成についてとか興味があります。

**Comment by hotchemi** [comment]
ゆるい感じで喋ったほうがユーザー受けが良い事が分かったのでゆるゆるやりましょう！

**Comment by hotchemi** [comment]
@takahirom podcastの注意点です！
- お茶飲んだり唾飲んだりする時はマイクから顔遠ざけた方が良さそう(飲み物の音は気にならない人もいるので難しい)
- 相槌は音が乗っちゃうのでやりすぎない方が良い(たまにする分にはOK)
  - と思ってたけど実は声が被らなければ笑い声とか相槌はOKなのかも！
- 各セクションの切れ目はちょっと間を空けると良い(後でNGの部分は切ったり編集しやすくなるので)

**Comment by takahirom** [comment]
@hotchemi ありがとうございます！
ゆるゆるやりたいですねー！(結構緊張しちゃっているのでなんとかしたい)
